=== paullewallencom/bpel-java-978-1-8496-8920-5/_/Code Bundle/9205EN_05_Codes/source_code/Validate_And_Transform/XSLT_Mapping/xsd/ModifiedCarSvcSchema.xsd
<?xml version="1.0" encoding="windows-1250" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://org.packt.car.ws.schema"
            targetNamespace="http://org.packt.car.ws.schema"
            elementFormDefault="qualified">
  <xsd:element name="WScars">
    <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="listCars" maxOccurs="unbounded">
                    <xsd:complexType>
                            <xsd:sequence>                                                            
                               <xsd:element name="carType" type="xsd:string"/>
                               <xsd:element name="buildYear" type="xsd:int"/>
                               <xsd:element name="milleage" type="xsd:int"/>
                               <xsd:element name="pricePerDay" type="xsd:int"/>
                               <xsd:element name="refNo" type="xsd:string"/>
                            </xsd:sequence>
                    </xsd:complexType>                                           
               </xsd:element>
            </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== paullewallencom/bpel-java-978-1-8496-8920-5/_/Code Bundle/9205EN_05_Codes/source_code/Validate_And_Transform/XSLT_Mapping/public_html/ForEachUseCase-Source.xml
<?xml version="1.0" encoding="UTF-8" ?>
<WScars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://org.packt.car.ws.schema file:/D:/sola/source_code/Validate_And_Transform/XSLT_Mapping/xsd/ModifiedCarSvcSchema.xsd" xmlns="http://org.packt.car.ws.schema">
   <listCars>
      <carType>Audi A4</carType>
      <buildYear>2012</buildYear>
      <milleage>2500</milleage>
      <pricePerDay>80</pricePerDay>
      <refNo>refNo5</refNo>
   </listCars>
   <listCars>
      <carType>BMW 730i</carType>
      <buildYear>2013</buildYear>
      <milleage>500</milleage>
      <pricePerDay>250</pricePerDay>
      <refNo></refNo>
   </listCars>
   <listCars>
      <carType>Mercedes Benz</carType>
      <buildYear>2010</buildYear>
      <milleage>60000</milleage>
      <pricePerDay>210</pricePerDay>      
   </listCars>
</WScars>
