=== paullewallencom/bpel-java-978-1-8496-8920-5/_/Code Bundle/9205EN_05_Codes/source_code/Validate_And_Transform/XSLT_Mapping/xsd/TempSchema.xsd
<?xml version="1.0" encoding="windows-1250" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://org.packt.temp"
            targetNamespace="http://org.packt.temp"
            elementFormDefault="qualified">
  <xsd:element name="TempElement">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="pieces" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== paullewallencom/bpel-java-978-1-8496-8920-5/_/Code Bundle/9205EN_05_Codes/source_code/Validate_And_Transform/XSLT_Mapping/public_html/TransformCarReservationData-Source.xml
<?xml version="1.0" encoding="UTF-8" ?>
<TempElement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://org.packt.temp file:/D:/sola/source_code/Validate_And_Transform/XSLT_Mapping/xsd/TempSchema.xsd" xmlns="http://org.packt.temp">
   <pieces>AUDI A8</pieces>
   <pieces>2013</pieces>
   <pieces>80000</pieces>
   <pieces>km</pieces>
   <pieces>60</pieces>
   <pieces>EUR</pieces>
   <pieces>ref: 343453</pieces>
</TempElement>
